proto:
	if [ -d "gen/api/v1" ]; then rm -rf gen/api/v1; fi && protoc --go_out=./gen --go-grpc_out=./gen api/v1/*.proto 

# if this doesn't work, 
# make sure you have installed go, proto and it's related compiler and necessary packages.
# please copy the below command and run it in your terminal manually and then hit "make proto" to generate the stubs 
path:
	export PATH="$PATH:$(go env GOPATH)/bin"